[folders]
2025-08-03_tmp = "E:\\fooocus\\images\\new\\2025-08-03_tmp"
2025-09-02 = "C:\\Users\\bradf\\Downloads\\2025-09-02"
2024-08-14 = "E:\\fooocus\\images\\new\\2024-08-14"
2024-04-12 = "E:\\fooocus\\images\\new\\2024-04-12"
2025-08-17 = "E:\\fooocus\\images\\new\\2025-08-17"
