[folders]
2025-08-03_tmp = "E:\\fooocus\\images\\new\\2025-08-03_tmp"
2024-08-14 = "E:\\fooocus\\images\\new\\2024-08-14"
2024-04-12 = "E:\\fooocus\\images\\new\\2024-04-12"
2025-08-17 = "E:\\fooocus\\images\\new\\2025-08-17"
_Imagesets = "C:\\Users\\bradf\\Downloads\\_Imagesets"
"2024-04-17 - island in space" = "E:\\fooocus\\images\\new\\2024-04-17 - island in space"
2024-04-18 = "E:\\fooocus\\images\\new\\2024-04-18"
2024-08-05 = "E:\\fooocus\\images\\new\\2024-08-05"
2025-10-06 = "E:\\fooocus\\images\\new\\2025-10-06"
2025-10-07 = "E:\\fooocus\\images\\new\\2025-10-07"
2025-10-08 = "E:\\fooocus\\images\\new\\2025-10-08"
2025-10-09 = "E:\\fooocus\\images\\new\\2025-10-09"
2025-10-05 = "E:\\fooocus\\images\\new\\2025-10-05"
2024-04-11 = "E:\\fooocus\\images\\new\\2024-04-11"
